### ISSUE TITLE
Application.get_extensions gives infinite recursion against Traits master

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#119]
The following script gives a `RecursionError` when run against Traits master. The change which triggered this looks very likely to be enthought/traits#382. The recursion seems to be a result of this change mixed with the `inspect` magic used by Envisage.

Here's the script
```python
from envisage.api import Application, ExtensionPoint, Plugin
from traits.api import List

class PluginA(Plugin):
    id = 'A'
    x  = ExtensionPoint(List, id='bob')

application = Application(plugins=[PluginA()])
application.get_extensions('bob')
```

And here's the start and end of the recursion error:
```
(envisage-test-3.6-pyqt)bash-3.2$ python ~/Desktop/envisage_bug.py 
Traceback (most recent call last):
  File "/Users/mdickinson/Desktop/envisage_bug.py", line 9, in <module>
    application.get_extensions('bob')
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/application.py", line 205, in get_extensions
    return self.extension_registry.get_extensions(extension_point_id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/extension_registry.py", line 71, in get_extensions
    return self._get_extensions(extension_point_id)[:]
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/provider_extension_registry.py", line 94, in _get_extensions
    extensions = self._initialize_extensions(extension_point_id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/provider_extension_registry.py", line 280, in _initialize_extensions
    extensions.append(provider.get_extensions(extension_point_id)[:])
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/plugin.py", line 135, in get_extensions
    extensions = self._harvest_methods(extension_point_id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/plugin.py", line 368, in _harvest_methods
    for name, value in inspect.getmembers(self):
  File "/Users/mdickinson/.edm/envs/envisage-test-3.6-pyqt/lib/python3.6/inspect.py", line 315, in getmembers
    value = getattr(object, key)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/extension_point.py", line 154, in get
    extensions = extension_registry.get_extensions(self.id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/application.py", line 205, in get_extensions
    return self.extension_registry.get_extensions(extension_point_id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/extension_registry.py", line 71, in get_extensions

[ ... many repetitions ... ]

  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/provider_extension_registry.py", line 280, in _initialize_extensions
    extensions.append(provider.get_extensions(extension_point_id)[:])
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/plugin.py", line 135, in get_extensions
    extensions = self._harvest_methods(extension_point_id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/plugin.py", line 368, in _harvest_methods
    for name, value in inspect.getmembers(self):
  File "/Users/mdickinson/.edm/envs/envisage-test-3.6-pyqt/lib/python3.6/inspect.py", line 315, in getmembers
    value = getattr(object, key)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/extension_point.py", line 154, in get
    extensions = extension_registry.get_extensions(self.id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/application.py", line 205, in get_extensions
    return self.extension_registry.get_extensions(extension_point_id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/extension_registry.py", line 71, in get_extensions
    return self._get_extensions(extension_point_id)[:]
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/provider_extension_registry.py", line 94, in _get_extensions
    extensions = self._initialize_extensions(extension_point_id)
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/provider_extension_registry.py", line 280, in _initialize_extensions
    extensions.append(provider.get_extensions(extension_point_id)[:])
  File "/Users/mdickinson/Enthought/ETS/envisage/envisage/plugin.py", line 122, in get_extensions
    trait_names = self.trait_names(contributes_to=extension_point_id)
  File "/Users/mdickinson/.edm/envs/envisage-test-3.6-pyqt/lib/python3.6/site-packages/traits/has_traits.py", line 3104, in trait_names
    return list(self.traits( **metadata ).keys())
  File "/Users/mdickinson/.edm/envs/envisage-test-3.6-pyqt/lib/python3.6/site-packages/traits/has_traits.py", line 3003, in traits
    for name, trt in list(self._instance_traits().items()):
RecursionError: maximum recursion depth exceeded while calling a Python object
(envisage-test-3.6-pyqt)bash-3.2$ 
```

**Comment by mdickinson** [comment]
One possible solution is to add some kind of loopback guard at some point in the recursion. The `_harvest_methods` method is a tempting place for this, given that it's the source of the unpleasantness in the first place: when called recursively, it should simply return an empty list.

**Comment by mdickinson** [comment]
On second thoughts, that's no good. It's not *just* getting the value for the `extensions` trait that's a problem here: getting the value for _any_ trait is potentially an issue, since it means we can't depend on evaluate-on-need in the plugin. We need a solution that avoids inspecting trait values altogether.

**Comment by rahulporuri** [comment]
@mdickinson is there a recommended solution to this issue? we ran into this when updating virtual core to the canopy data 0.14. We needed the latest traits to fix a different issue.

**Comment by rkern** [comment]
Can we inspect the _class_ for methods instead of the instance?
