### ISSUE TITLE
setup.py test failure

### ISSUE THREAD

**Issue by opoplawski** [enthought/envisage#133]
```
ERROR: fbi_plugin_definition (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: fbi_plugin_definition
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/envisage-4.7.1/envisage/plugins/debug/fbi_plugin_definition.py", line 17, in <module>
    from envisage.core.core_plugin_definition \
ModuleNotFoundError: No module named 'envisage.core'
```
There seem to be a number of references to envisage.core that does not appear to exists:
```
envisage-4.7.1/envisage/developer/code_browser/module.py:        '/enthought/envisage/core/core_plugin_definition.py'
envisage-4.7.1/envisage/developer/code_browser/module.py:        'envisage.core.core_plugin_definition'
envisage-4.7.1/envisage/plugins/debug/fbi_plugin_definition.py:from envisage.core.core_plugin_definition \
envisage-4.7.1/examples/plugins/single_project/sample_project/data/plugin/plugin_definition.py:from envisage.core.core_plugin_definition import ApplicationObject
```

**Comment by opoplawski** [comment]
Also:
```
ERROR: api (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: api
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/envisage-4.7.1/envisage/plugins/ipython_shell/view/api.py", line 1, in <module>
    from .ipython_shell_view import IPythonShellView
  File "/builddir/build/BUILD/envisage-4.7.1/envisage/plugins/ipython_shell/view/ipython_shell_view.py", line 9, in <module>
    from IPython.kernel.core.interpreter import Interpreter
ModuleNotFoundError: No module named 'IPython.kernel.core'
```

**Comment by rkern** [comment]
[`nose`](https://pypi.org/project/nose/) is our test runner: https://github.com/enthought/envisage/blob/master/tox.ini#L9

And we use [`etstool.py`](https://github.com/enthought/envisage/blob/master/etstool.py) to manage the appropriate test environment that includes all of the soft, optional dependencies.

**Comment by mdickinson** [comment]
Closing this issue as out of date: the FBI plugin has been removed, and the test suite should now run cleanly under unittest.
