### ISSUE TITLE
Tests fail with python 3.7

### ISSUE THREAD

**Issue by opoplawski** [enthought/envisage#135]
I'm seeing:
```
ERROR: test_exclude_multiple (envisage.tests.egg_plugin_manager_test_case.EggPluginManagerTestCase)
exclude multiple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/envisage-4.7.1/envisage/tests/egg_plugin_manager_test_case.py", line 116, in test_exclude_multiple
    self._add_eggs_on_path([self.egg_dir])
  File "/builddir/build/BUILD/envisage-4.7.1/envisage/tests/egg_based_test_case.py", line 67, in _add_eggs_on_path
    raise SystemError('Cannot find eggs %s' % errors)
SystemError: Cannot find eggs {}
```
And I think that is because there are no 3.7 eggs in the testing directory.

**Comment by mdickinson** [comment]
Thanks for the report. This should be fixed by #136.
