### ISSUE TITLE
test_tasks_application fails with failure to import `pygments` in Python 3.7 venv

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#209]
While testing the 4.8.0 release, I get the following failure while executing `python -m unittest discover -v envisage` in a venv.

Contents of the environment:
```
(entest) mirzakhani:Desktop mdickinson$ pip freeze
apptools==4.4.0
configobj==5.0.6
envisage==4.8.0
nose==1.3.7
pyface==6.1.2
PyQt5==5.13.0
PyQt5-sip==4.19.18
six==1.12.0
traits==5.1.2
traitsui==6.1.3
```

And the test error:

```
======================================================================
ERROR: envisage.ui.tasks.tests.test_tasks_application (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: envisage.ui.tasks.tests.test_tasks_application
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/envisage/ui/tasks/tests/test_tasks_application.py", line 18, in <module>
    from envisage.ui.tasks.api import TasksApplication
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/envisage/ui/tasks/api.py", line 11, in <module>
    from .task_extension import TaskExtension
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/envisage/ui/tasks/task_extension.py", line 10, in <module>
    from pyface.tasks.action.api import SchemaAddition
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/tasks/action/api.py", line 19, in <module>
    from .task_action import (
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/tasks/action/task_action.py", line 14, in <module>
    from pyface.tasks.api import Editor, Task, TaskPane
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/tasks/api.py", line 14, in <module>
    from .split_editor_area_pane import SplitEditorAreaPane
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/tasks/split_editor_area_pane.py", line 3, in <module>
    SplitEditorAreaPane = toolkit_object('tasks.split_editor_area_pane:'
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/base_toolkit.py", line 144, in __call__
    module = import_module(mname, package)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/ui/qt4/tasks/split_editor_area_pane.py", line 13, in <module>
    from pyface.api import FileDialog
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/api.py", line 36, in <module>
    from .python_editor import PythonEditor
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/python_editor.py", line 21, in <module>
    PythonEditor = toolkit_object('python_editor:PythonEditor')
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/base_toolkit.py", line 144, in __call__
    module = import_module(mname, package)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/ui/qt4/python_editor.py", line 27, in <module>
    from pyface.ui.qt4.code_editor.code_widget import AdvancedCodeWidget
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/ui/qt4/code_editor/code_widget.py", line 23, in <module>
    from .pygments_highlighter import PygmentsHighlighter
  File "/Users/mdickinson/Desktop/entest/lib/python3.7/site-packages/pyface/ui/qt4/code_editor/pygments_highlighter.py", line 14, in <module>
    from pygments.lexer import RegexLexer, _TokenType, Text, Error
ModuleNotFoundError: No module named 'pygments'

```

**Comment by mdickinson** [comment]
This is a PyFace issue: `import pyface.api` fails with current PyFace.

**Comment by mdickinson** [comment]
But: we should skip the relevant test if `pygments` is not installed, and also consider what the runtime behaviour is when `pygments` is not installed - is there an obvious indication to the user of what's wrong in that situation?

**Comment by mdickinson** [comment]
Still an issue with 4.9.0.

**Comment by mdickinson** [comment]
It looks as though this was fixed upstream at some point. I can run the test suite to completion (with no skips) without `pygments` being present.
