### ISSUE TITLE
core_plugin_test_case, package_plugin_manager_test_case.py error in 4.3.0

### ISSUE THREAD

**Issue by idella** [enthought/envisage#21]
I've run these a number of times (once was enough) and they appear legitimate errors, possibly regressions.

ERROR: dynamically added category

---

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/tests/core_plugin_test_case.py", line 229, in test_dynamically_added_category
    class Baz(HasTraits):
  File "/usr/lib64/python2.7/site-packages/traits/has_traits.py", line 659, in **new**
    listener( klass )
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/class_load_hook.py", line 63, in on_class_loaded
    self.on_load(cls)
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/core_plugin.py", line 245, in import_and_add_category
    category_cls = self.application.import_symbol(category.class_name)
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/application.py", line 249, in import_symbol
    return self._import_manager.import_symbol(symbol_path)
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/import_manager.py", line 42, in import_symbol
    module_name, globals(), locals(), [symbol_name]
ImportError: No module named baz_category
-------------------- >> begin captured logging << --------------------
envisage.application: DEBUG: ---------- application starting ----------
envisage.plugin_manager: DEBUG: plugin envisage.core starting
envisage.provider_extension_registry: DEBUG: extensions to <envisage.preferences> <[[]]>
apptools.preferences.preferences: DEBUG: loading preferences from </var/tmp/portage/dev-python/envisage-4.3.0-r1/homedir/.enthought/core.plugin.test/preferences.ini>
envisage.provider_extension_registry: DEBUG: extensions to <envisage.class_load_hooks> <[[]]>
envisage.provider_extension_registry: DEBUG: extensions to <envisage.categories> <[[]]>
envisage.provider_extension_registry: DEBUG: extensions to <envisage.service_offers> <[[]]>
envisage.plugin_manager: DEBUG: plugin envisage.core started
envisage.application: DEBUG: ---------- application started ----------
--------------------- >> end captured logging << ---------------------

ERROR: dynamically class load hooks

---

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/tests/core_plugin_test_case.py", line 339, in test_dynamically_added_class_load_hooks
    class Baz(HasTraits):
  File "/usr/lib64/python2.7/site-packages/traits/has_traits.py", line 659, in **new**
    listener( klass )
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/class_load_hook.py", line 63, in on_class_loaded
    self.on_load(cls)
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/core_plugin.py", line 245, in import_and_add_category
    category_cls = self.application.import_symbol(category.class_name)
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/application.py", line 249, in import_symbol
    return self._import_manager.import_symbol(symbol_path)
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/import_manager.py", line 42, in import_symbol
    module_name, globals(), locals(), [symbol_name]
ImportError: No module named baz_category
-------------------- >> begin captured logging << --------------------
envisage.application: DEBUG: ---------- application starting ----------
envisage.plugin_manager: DEBUG: plugin envisage.core starting
envisage.provider_extension_registry: DEBUG: extensions to <envisage.preferences> <[[]]>
apptools.preferences.preferences: DEBUG: loading preferences from </var/tmp/portage/dev-python/envisage-4.3.0-r1/homedir/.enthought/core.plugin.test/preferences.ini>
envisage.provider_extension_registry: DEBUG: extensions to <envisage.class_load_hooks> <[[]]>
envisage.provider_extension_registry: DEBUG: extensions to <envisage.categories> <[[]]>
envisage.provider_extension_registry: DEBUG: extensions to <envisage.service_offers> <[[]]>
envisage.plugin_manager: DEBUG: plugin envisage.core started
envisage.application: DEBUG: ---------- application started ----------
--------------------- >> end captured logging << ---------------------

FAIL: test_only_find_plugins_matching_a_wildcard_in_the_include_list (envisage.tests.package_plugin_manager_test_case.PackagePluginManagerTestCase)

---

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/tests/package_plugin_manager_test_case.py", line 78, in test_only_find_plugins_matching_a_wildcard_in_the_include_list
    self._test_start_and_stop(plugin_manager, expected)
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/tests/package_plugin_manager_test_case.py", line 148, in _test_start_and_stop
    self.assertEqual(expected, [plugin.id for plugin in plugin_manager])
AssertionError: Lists differ: ['orange', 'pear'] != ['pear', 'orange']

First differing element 0:
orange
pear
- ['orange', 'pear']
- ['pear', 'orange']
  -------------------- >> begin captured logging << --------------------
  envisage.package_plugin_manager: DEBUG: Looking for plugins in /var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/tests/plugins/pear
  envisage.package_plugin_manager: DEBUG: package plugin manager found plugins <[<pear.pear_plugin.PearPlugin object at 0x355cd10>, <orange.orange_plugin.OrangePlugin object at 0x355cbf0>]>
  --------------------- >> end captured logging << ---------------------
# 

FAIL: test_only_find_plugins_whose_ids_are_in_the_include_list (envisage.tests.package_plugin_manager_test_case.PackagePluginManagerTestCase)

---

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/tests/package_plugin_manager_test_case.py", line 58, in test_only_find_plugins_whose_ids_are_in_the_include_list
    self._test_start_and_stop(plugin_manager, expected)
  File "/var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/tests/package_plugin_manager_test_case.py", line 148, in _test_start_and_stop
    self.assertEqual(expected, [plugin.id for plugin in plugin_manager])
AssertionError: Lists differ: ['orange', 'pear'] != ['pear', 'orange']

First differing element 0:
orange
pear
- ['orange', 'pear']
- ['pear', 'orange']
  -------------------- >> begin captured logging << --------------------
  envisage.package_plugin_manager: DEBUG: Looking for plugins in /var/tmp/portage/dev-python/envisage-4.3.0-r1/work/envisage-4.3.0/envisage/tests/plugins/pear
  envisage.package_plugin_manager: DEBUG: package plugin manager found plugins <[<pear.pear_plugin.PearPlugin object at 0x356d1d0>, <orange.orange_plugin.OrangePlugin object at 0x356d290>]>
  --------------------- >> end captured logging << ---------------------

---

Ran 185 tests in 3.606s

FAILED (errors=2, failures=2)

ImportError: No module named baz_category

How on earth do you get it attempting to import baz_category?? Ought it not be importing plain baz ??

 $ python -V         Python 2.7.3

Oh, is this packages intended to support py2.6"
- python2_6: running distutils-r1_run_phase python_test yields

---

Ran 162 tests in 3.722s

FAILED (errors=17, failures=9)
Looks like we could take this as a no.

**Comment by mdickinson** [comment]
This was fixed in #22.
