### ISSUE TITLE
Task Layout Persistence

### ISSUE THREAD

**Issue by jirhiker** [enthought/envisage#29]
VSplitter and HSplitter.items should be defined as List(Either(PaneItem, Tabbed, Splitter))

you can define a layout like ... left=HSplitter(VSplitter(...), VSplitter(...))

but the following exception is raised when a task window with this layout is closed
```
traits                                  : 
2013-09-18 21:16:10,283 ERROR   (MainThread) Exception occurred in traits notification handler for object: <envisage.ui.tasks.task_window.TaskWindow object at 0x11eff1b30>, trait: closing, old value: <undefined>, new value: <traits.has_traits.Vetoable object at 0x120b45470>
Traceback (most recent call last):
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 535, in rebind_call_3
    object, trait_name, new )
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 455, in dispatch
    handler( *args )
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/envisage/ui/tasks/tasks_application.py", line 412, in _on_window_closing
    window_layout = window.get_window_layout()
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyface/tasks/task_window.py", line 299, in get_window_layout
    layout = self._window_backend.get_layout()
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyface/ui/qt4/tasks/task_window_backend.py", line 85, in get_layout
    self._main_window_layout.get_layout(layout)
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyface/ui/qt4/tasks/main_window_layout.py", line 41, in get_layout
    sublayout = self.get_layout_for_area(q_dock_area, include_sizes)
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyface/ui/qt4/tasks/main_window_layout.py", line 91, in get_layout_for_area
    item = HSplitter(item1, item2)
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pyface/tasks/task_layout.py", line 78, in __init__
    self.items = list(items)
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_types.py", line 2187, in validate
    return TraitListObject( self, object, name, value )
  File "/Users/ross/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_handlers.py", line 2418, in **init**
    raise excp
TraitError: Each element of the 'items' trait of a HSplitter instance must be an implementor of, or can be adapted to implement, PaneItem or None or an implementor of, or can be adapted to implement, Tabbed or None or an instance of the same type as the receiver or None, but a value of VSplitter(PaneItem('pychron.analysis_edit.unknowns', height=184, width=252), VSplitter(PaneItem('pychron.analysis_edit.references', height=182, width=252), PaneItem('pychron.analysis_edit.controls', height=124, width=252))) <class 'pyface.tasks.task_layout.VSplitter'> was specified.
```

**Comment by rahulporuri** [comment]
Note : I edited the issue to format the error message and make it easier to read.

**Comment by corranwebster** [comment]
This was a Pyface issue and looks to be long resolved:
https://github.com/enthought/pyface/blob/6c9ae8328acef522bffd71e1d26aa502de926b67/pyface/tasks/task_layout.py#L153-L160
