### ISSUE TITLE
Test against wxPython v4.x instead of v3.x

### ISSUE THREAD

**Issue by rahulporuri** [enthought/envisage#312]
At the moment, we seem to be testing against v 3.x of wxPython where as ETS (Pyface/Traitsui) recommends using wxPython 4.x. We should be able to use code from the `etstool.py` module in traitsui/pyface to be able to install the relevant version of wxPython correctly.

https://github.com/enthought/envisage/blob/ae477a4e4919681006c9e84bb4f9edb77b65bba8/etstool.py#L129.

**Comment by aaronayres35** [comment]
I believe currently we are not testing against wx at all.  It is not listed in supported combinations:
https://github.com/enthought/envisage/blob/0fe955297a13462d09c3b5fe2b60ef78c5ab6fba/etstool.py#L100-L102

If I try to run `python etstool.py install --toolkit=wx` in a bootstrap edm environment I see the following:
```
$ python etstool.py install --toolkit=wx
Traceback (most recent call last):
  File "etstool.py", line 551, in <module>
    cli()
  File "/Users/aayres/.edm/envs/bootstrap/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/aayres/.edm/envs/bootstrap/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/aayres/.edm/envs/bootstrap/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/aayres/.edm/envs/bootstrap/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/aayres/.edm/envs/bootstrap/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "etstool.py", line 204, in install
    parameters = get_parameters(edm, runtime, toolkit, environment)
  File "etstool.py", line 466, in get_parameters
    raise RuntimeError(msg.format(**parameters))
RuntimeError: Python 3.6 and toolkit wx not supported by test environments
```

**Comment by aaronayres35** [comment]
> I believe currently we are not testing against wx at all. 

Looks like this change was made in #225 when we stopped testing the package in python2 on CI.
