### ISSUE TITLE
A testing error occurs when the optional dependency ipykernel is not installed

### ISSUE THREAD

**Issue by kihneman** [enthought/envisage#387]
When running the envisage tests with nosetests, there is an error if ipykernel is not installed. It would help those testing envisage if either ipykernel was included as a test dependency in the setup.py, or if the envisage tests would detect whether or not ipykernel was installed rather than complaining.

There is no urgency from the point of view of the build team since ipykernel is being added as a test dependency in the recipe.

Here is the traceback:
```
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'ipykernel')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\site-packages\nose\loader.py", line 419, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\site-packages\envisage\tests\test_ids.py", line 15, in <module>
    from envisage.plugins.ipython_kernel.api import IPythonKernelPlugin
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\site-packages\envisage\plugins\ipython_kernel\api.py", line 17, in <module>
    from envisage.plugins.ipython_kernel.actions import StartQtConsoleAction
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\site-packages\envisage\plugins\ipython_kernel\actions.py", line 13, in <module>
    from .internal_ipkernel import InternalIPKernel
  File "C:\Users\kkihneman\.edm-build\envs\build-env\lib\site-packages\envisage\plugins\ipython_kernel\internal_ipkernel.py", line 20, in <module>
    import ipykernel.connect
ModuleNotFoundError: No module named 'ipykernel'

----------------------------------------------------------------------
```

**Comment by kitchoi** [comment]
Thank you @kihneman. Agreed, and sorry for the inconvenience. This has been noticed in #369 recently and has not been fixed.

**Comment by kihneman** [comment]
Sorry for not noticing that this issue already existed. You can close as duplicate if you like.

**Comment by kitchoi** [comment]
Thank you for the report nonetheless - so we know this is affecting the build team!
Closing as duplicate.
