### ISSUE TITLE
Test suite fails on a minimal install: No module named 'ipykernel'

### ISSUE THREAD

**Issue by mdickinson** [enthought/envisage#420]
The test suite fails on a minimal `pip` install of Envisage 6.0.0 into a clean environment (see shell session below).

We should fix the relevant test so that it's skipped if `ipykernel` isn't available. It may also be useful to have workflows that test a minimal install of Envisage, similar to the existing [`run-core-traits-tests` workflow](https://github.com/enthought/traits/blob/master/.github/workflows/run-core-traits-tests.yml) for Traits.

```
mdickinson@mirzakhani Desktop % python -m venv --clear ~/.venvs/envisage
mdickinson@mirzakhani Desktop % source ~/.venvs/envisage/bin/activate
(envisage) mdickinson@mirzakhani Desktop % pip install envisage
Collecting envisage
  Using cached envisage-6.0.0.tar.gz (196 kB)
Collecting apptools
  Using cached apptools-5.1.0-py3-none-any.whl
Requirement already satisfied: setuptools in /Users/mdickinson/.venvs/envisage/lib/python3.9/site-packages (from envisage) (56.0.0)
Collecting traits>=6.2
  Using cached traits-6.2.0-cp39-cp39-macosx_10_14_x86_64.whl (5.0 MB)
Collecting traitsui
  Using cached traitsui-7.2.1.tar.gz (6.7 MB)
Collecting configobj
  Using cached configobj-5.0.6-py3-none-any.whl
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyface>=7.3.0
  Using cached pyface-7.3.0-py3-none-any.whl
Collecting importlib-resources>=1.1.0
  Using cached importlib_resources-5.1.4-py3-none-any.whl (26 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-4.5.0-py3-none-any.whl (17 kB)
Collecting zipp>=3.1.0
  Using cached zipp-3.4.1-py3-none-any.whl (5.2 kB)
Using legacy 'setup.py install' for envisage, since package 'wheel' is not installed.
Using legacy 'setup.py install' for traitsui, since package 'wheel' is not installed.
Installing collected packages: zipp, traits, importlib-resources, importlib-metadata, six, pyface, traitsui, configobj, apptools, envisage
    Running setup.py install for traitsui ... done
    Running setup.py install for envisage ... done
Successfully installed apptools-5.1.0 configobj-5.0.6 envisage-6.0.0 importlib-metadata-4.5.0 importlib-resources-5.1.4 pyface-7.3.0 six-1.16.0 traits-6.2.0 traitsui-7.2.1 zipp-3.4.1
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/Users/mdickinson/.venvs/envisage/bin/python -m pip install --upgrade pip' command.
(envisage) mdickinson@mirzakhani Desktop % python -m unittest discover envisage    
..sssssssssssssssssssssss....................................................................................................E...........................................................................................................ssss
======================================================================
ERROR: envisage.tests.test_ids (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: envisage.tests.test_ids
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/Users/mdickinson/.venvs/envisage/lib/python3.9/site-packages/envisage/tests/test_ids.py", line 15, in <module>
    from envisage.plugins.ipython_kernel.api import IPythonKernelPlugin
  File "/Users/mdickinson/.venvs/envisage/lib/python3.9/site-packages/envisage/plugins/ipython_kernel/api.py", line 17, in <module>
    from envisage.plugins.ipython_kernel.actions import StartQtConsoleAction
  File "/Users/mdickinson/.venvs/envisage/lib/python3.9/site-packages/envisage/plugins/ipython_kernel/actions.py", line 13, in <module>
    from .internal_ipkernel import InternalIPKernel
  File "/Users/mdickinson/.venvs/envisage/lib/python3.9/site-packages/envisage/plugins/ipython_kernel/internal_ipkernel.py", line 20, in <module>
    import ipykernel.connect
ModuleNotFoundError: No module named 'ipykernel'


----------------------------------------------------------------------
Ran 237 tests in 0.803s

FAILED (errors=1, skipped=27)
```

**Comment by mdickinson** [comment]
Looks like this was a duplicate of #369.
