### ISSUE TITLE
python 3.5 test failure

### ISSUE THREAD

**Issue by opoplawski** [enthought/envisage#65]
Is python3 supported?  I'm getting:

```
/usr/bin/python3 setup.py test
running test
running egg_info
writing entry points to envisage.egg-info/entry_points.txt
writing dependency_links to envisage.egg-info/dependency_links.txt
writing envisage.egg-info/PKG-INFO
writing requirements to envisage.egg-info/requires.txt
writing top-level names to envisage.egg-info/top_level.txt
reading manifest file 'envisage.egg-info/SOURCES.txt'
writing manifest file 'envisage.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 158, in <module>
    zip_safe = False,
  File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3.5/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/usr/lib/python3.5/site-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/usr/lib64/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib64/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3.5/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.5/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.5/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.5/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3.5/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/envisage-4.5.0/envisage/developer/ui/api.py", line 1, in <module>
    from .view.plugin_browser import browse_plugin
  File "/builddir/build/BUILD/envisage-4.5.0/envisage/developer/ui/view/plugin_browser.py", line 11, in <module>
    class ExtensionPointModel(Hastraits):
NameError: name 'Hastraits' is not defined
```

**Comment by opoplawski** [comment]
Still getting this with python 3.7.  Am I just missing a dependency?  I have traits and traitsui installed.

**Comment by rahulporuri** [comment]
@opoplawski Thanks for reporting/updating this issue. Python 3 is definitely supported by `envisage` but it looks like there are parts of the code base which need to get fixed/updated.

If you are interested in running the test suite, you can take a look at the etstool module and the test click command - https://github.com/enthought/envisage/blob/63d9329a8abdb76466fd75f18beab7b8490c5daf/etstool.py#L156-L179 

I've opened PR #130 to fix a few issues. The changes in the branch should allow you to successfully run `python setup.py` test, but the test suite fails. See PR for more details.

**Comment by rahulporuri** [comment]
Closing as #130 fixes the issue of not being able to run `python setup.py test`.

**Comment by mdickinson** [comment]
So the CI is using nosetests; at some point, we should investigate why unittest discover manages to find and run these failing tests while nosetests doesn't. (It's usually the other way around.)
